# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXXnSnsI95QrHqrxIW45QSmq61758l7N
"""

import datetime
import hashlib
import json
import streamlit as st

class Blockchain:
    def __init__(self):
        self.chain = []
        # Create the genesis block
        self.create_block(proof=1, previous_hash='0')

    def create_block(self, proof, previous_hash):
        block = {
            'index': len(self.chain) + 1,
            'timestamp': str(datetime.datetime.now()),
            'proof': proof,
            'previous_hash': previous_hash
        }
        self.chain.append(block)
        return block

    def get_previous_block(self):
        return self.chain[-1]

    def hash(self, block):
        encoded_block = json.dumps(block, sort_keys=True).encode()
        return hashlib.sha256(encoded_block).hexdigest()

    def is_chain_valid(self, chain):
        previous_block = chain[0]
        block_index = 1
        while block_index < len(chain):
            block = chain[block_index]
            if block['previous_hash'] != self.hash(previous_block):
                return False
            previous_block = block
            block_index += 1
        return True

# --- Streamlit UI ---
st.set_page_config(page_title="Simple Python Blockchain", layout="wide")
st.title("⛓️ Simple Blockchain Demo")

# Initialize the blockchain in the session state so it persists during reruns
if 'blockchain' not in st.session_state:
    st.session_state.blockchain = Blockchain()

# Sidebar actions
st.sidebar.header("Controls")

if st.sidebar.button("Mine New Block"):
    blockchain = st.session_state.blockchain
    prev_block = blockchain.get_previous_block()
    prev_hash = blockchain.hash(prev_block)
    new_block = blockchain.create_block(proof=100, previous_hash=prev_hash)
    st.sidebar.success(f"Block #{new_block['index']} Mined!")

if st.sidebar.button("Check Validity"):
    is_valid = st.session_state.blockchain.is_chain_valid(st.session_state.blockchain.chain)
    if is_valid:
        st.sidebar.info("The Blockchain is valid! ✅")
    else:
        st.sidebar.error("The Blockchain is invalid! ❌")

# Display the Chain
st.subheader("The Ledger")
for block in st.session_state.blockchain.chain:
    with st.expander(f"Block #{block['index']}"):
        st.json(block)